name: Azure Login Test

on:
  push:
    branches:
      - main


jobs:
  azure-login:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDS }}

      - name: Show Current Azure Account
        run: az account show --output table

      - name: 'Set up Java'
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - uses: stCarolas/setup-maven@v4
        with:
          maven-version: '3.6.3'

      - name: Test
        run: |
           ls -lh

      - name: Deploy
        run: |
           mvn clean package azure-functions:deploy
