name: Azure Login Test

on:
  push:
    branches:
      - main


jobs:
  azure-login:
    runs-on: self-hosted
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDS }}

      - name: Show Current Azure Account
        run: az account show --output table
